pipeline:
  publish:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: josmo/grannec-web
    auto_tag: true
    file: Dockerfile
    when:
      event: [ push, tag ]

  deploy-latest-chart:
    image: quay.io/ipedrazas/drone-helm
    chart: ./charts/grannec-web
    values:
    - annotations.deployedDate="${DRONE_JOB_STARTED}"
    - annotations.buildNumber="${DRONE_BUILD_NUMBER}"
    release: "gw-latest"
    namespace: josmo
    debug: true
    wait: true
    secrets: [ api_server, kubernetes_token ]
    when:
      event: [ push, master ]


#  deploy_dev:
#    image: peloton/drone-k8s-deployment
#    pull: true
#    url: https://rancher.pelo.tech/k8s/clusters/c-ss4wc
#    secrets: [ kubernetes_token ]
#    namespaces: josmo
#    deployment_names: grannec-web
#    docker_image: "josmo/grannec-web:latest"
#    container_names: grannec-web
#    when:
#      event: [ push ]
#      branch: [ master ]



branches: [ master ]
