kind: pipeline
name: default

platform:
  os: linux
  arch: amd64
steps:
  - name: publish
    pull: default
    image: plugins/docker
    settings:
      auto_tag: true
      file: Dockerfile
      repo: josmo/grannec-web
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    when:
      branch:
        - master
      event:
        - push
  - name: helm-lint
    pull: default
    image: pelotech/drone-helm3:0.14.2
    settings:
      helm_command: lint
      chart: ./helm/grannec-web
      wait: true
    environment:
      API_SERVER:
        from_secret: api_server
      KUBERNETES_TOKEN:
        from_secret: kubernetes_token
    when:
      branch:
        - master
      event:
        - push
  - name: deploy-dev
    pull: default
    image: pelotech/drone-helm3:0.14.2
    settings:
      chart: ./helm/grannec-web
      namespace: josmo
      release: josmo
      timeout: 200s
      update_dependencies: true
      values:
        - "annotations.deployedDate=\"${DRONE_BUILD_CREATED}\""
        - "annotations.buildNumber=\"${DRONE_BUILD_NUMBER}\""
      wait: true
    environment:
      API_SERVER:
        from_secret: api_server
      KUBERNETES_TOKEN:
        from_secret: kubernetes_token
    when:
      branch:
        - master
      event:
        - push



