{{- if .Values.certificate.enabled -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $fullName }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: {{ .Values.certificate.commonName }}
  dnsNames:
  {{- range .Values.certificate.domains }}
    - {{ . }}
  {{- end }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      {{- range .Values.certificate.domains }}
        - {{ . }}
      {{- end }}
      {{- range .Values.ingress.tls }}
      {{-  end }}
{{- end }}