apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "grannec-web.fullname" . }}
  labels:
    app: {{ template "grannec-web.name" . }}
    chart: {{ template "grannec-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    'workload.user.cattle.io/workloadselector': {{ template "grannec-web.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "grannec-web.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "grannec-web.name" . }}
        release: {{ .Release.Name }}
        'workload.user.cattle.io/workloadselector': {{ template "grannec-web.fullname" . }}
      annotations:
        buildNumber: {{ .Values.annotations.buildNumber | quote }}
        deployedDate: {{ .Values.annotations.deployedDate | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
